package config

const (
	WIN_WIDTH  = 1071
	WIN_HEIGHT = 534

	PRE_MARKED_LINE = WIN_WIDTH / 5
	SEMI_CIRC_RADI  = WIN_WIDTH / 6
    BASE_POWER = 1.5
    MAX_VELOCITY = 50

    DRAG = 0.8
    FIXED_TIMESTAMP_LOOP = 0.01666

    MAX_ACCEL = 20
)
